### ISSUE TITLE
run "make" problem

### ISSUE THREAD

**Issue by Little0213** [guicho271828/CAP#4]
Dear professor, when I run "make", I encountered the following problems, can you please help me solve it?

ros dynamic-space-size=16000 -- -e "(setf ql:*local-project-directories* '(#p\"/home/ls/CAP/\"))(ql:register-local-projects)" dump executable ./component-planner.ros
WARNING: :SB-EVAL is no longer present in *FEATURES*
To load "pddl.component-planner":
  Load 1 ASDF system:
    pddl.component-planner
; Loading "pddl.component-planner"
..........
; file: /home/ls/CAP/pddl.component-abstraction/src/tasks.lisp
; in: DEFMETHOD PRINT-OBJECT (ABSTRACT-COMPONENT-TASK T)
;     (TRIVIA.LEVEL2:MATCH PDDL.COMPONENT-ABSTRACTION::AC-TASK
;       ((PDDL.COMPONENT-ABSTRACTION::ABSTRACT-COMPONENT-TASK
;         (PDDL.COMPONENT-ABSTRACTION::AC (AND PDDL.COMPONENT-ABSTRACTION::AC #))
;         PDDL.COMPONENT-ABSTRACTION::MULTIARY-INIT
;         PDDL.COMPONENT-ABSTRACTION::MULTIARY-GOAL
;         PDDL.COMPONENT-ABSTRACTION::UNARY-INIT
;         PDDL.COMPONENT-ABSTRACTION::UNARY-GOAL)
;        (LET ((*PRINT-ESCAPE* T))
;          (FORMAT PDDL.COMPONENT-ABSTRACTION::S "~<A-TASK ~;~@{~w ~w~^ ~:_~}~:>"
;                  `(:AC ,PDDL.COMPONENT-ABSTRACTION::AC ,@# ,@# ,@# ,@#)))))
; 
; caught ERROR:
;   (during macroexpansion of (SB-PCL::%DEFMETHOD-EXPANDER PRINT-OBJECT ...))
;   Failed to deduce the way access the slot MULTIARY-INIT
.Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=85182 "main thread" RUNNING
                                                          {10012B8003}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "pddl.component-abstraction" "src" "tasks">

Backtrace for: #<SB-THREAD:THREAD tid=85182 "main thread" RUNNING {10012B8003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {101BF260A3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {101BF260A3}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {101BF260A3}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pddl.component-abstraction" "src" "tasks">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pddl.component-abstraction" "src" "tasks">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pddl.component-abstraction" "src" "tasks">)
6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
7: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "pddl.component-abstraction" "src" "tasks">) [fast-method]
8: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100AC4BE73}>) [fast-method]
9: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
10: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100AC4BE73}>) [fast-method]
11: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "pddl.component-planner"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
12: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "pddl.component-planner"> :VERBOSE NIL)
13: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
14: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "pddl.component-planner"> :VERBOSE NIL) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "pddl.component-planner" :VERBOSE NIL)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "pddl.component-planner" :VERBOSE NIL) [fast-method]
18: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100AC643DB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100AC4753B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "pddl.component-planner" :VERBOSE NIL) [fast-method]
22: (ASDF/OPERATE:LOAD-SYSTEM "pddl.component-planner" :VERBOSE NIL)
23: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {100AC458AB}>)
24: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "pddl.component-planner" :PROMPT NIL)
25: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100AA9A1EB}>) [fast-method]
26: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1006D865B3}> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {100AA9A1EB}>) [fast-method]
27: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) :PDDL.COMPONENT-PLANNER :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
28: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100AA953DB}>)
29: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :PDDL.COMPONENT-PLANNER) #<NULL-LEXENV>)
30: (EVAL-TLF (QUICKLISP-CLIENT:QUICKLOAD :PDDL.COMPONENT-PLANNER) NIL NIL)
31: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (QUICKLISP-CLIENT:QUICKLOAD :PDDL.COMPONENT-PLANNER) NIL)
32: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/ls/CAP/./component-planner.ros" {100AA252B3}> #<SB-IMPL::STRING-INPUT-STREAM {100AA263F3}>) {100AA26483}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
33: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/ls/CAP/./component-planner.ros" {100AA252B3}> #<SB-IMPL::STRING-INPUT-STREAM {100AA263F3}>) {100AA26483}> NIL)
34: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7FBD22336ACB}> #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/ls/CAP/./component-planner.ros" {100AA252B3}> #<SB-IMPL::STRING-INPUT-STREAM {100AA263F3}>) {100AA26483}> NIL #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/ls/CAP/./component-planner.ros" {100AA252B3}> #<SB-IMPL::STRING-INPUT-STREAM {100AA263F3}>) {100AA26483}>)
35: (LOAD #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/ls/CAP/./component-planner.ros" {100AA252B3}> #<SB-IMPL::STRING-INPUT-STREAM {100AA263F3}>) {100AA26483}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
36: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /home/ls/CAP/./component-planner.ros" {100AA252B3}>)
37: (ROSWELL:SCRIPT #P"./component-planner.ros")
38: (ROS.SCRIPT.DUMP::EXECUTABLE ROSWELL.DUMP.SBCL::SBCL ("./component-planner.ros"))
39: (ROS.SCRIPT.DUMP::MAIN "executable" "./component-planner.ros")
40: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
41: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
42: (EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) NIL NIL)
43: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) NIL)
44: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {100957C2A3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
45: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {100957C2A3}> NIL)
46: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7FBD223375CB}> #<CONCATENATED-STREAM :STREAMS NIL {100957C2A3}> NIL #<CONCATENATED-STREAM :STREAMS NIL {100957C2A3}>)
47: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {100957C2A3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
48: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /etc/roswell/dump.ros" {1009579553}>)
49: (ROSWELL:SCRIPT "/etc/roswell/dump.ros" "executable" "./component-planner.ros")
50: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:EVAL "(setf ql:*local-project-directories* '(#p\"/home/ls/CAP/\"))(ql:register-local-projects)") (:SCRIPT "/etc/roswell/dump.ros" "executable" "./component-planner.ros") (:QUIT NIL)))
51: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:EVAL "(setf ql:*local-project-directories* '(#p\"/home/ls/CAP/\"))(ql:register-local-projects)") (:SCRIPT "/etc/roswell/dump.ros" "executable" "./component-planner.ros") (:QUIT NIL)))) #<NULL-LEXENV>)
52: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:EVAL "(setf ql:*local-project-directories* '(#p\"/home/ls/CAP/\"))(ql:register-local-projects)") (:SCRIPT "/etc/roswell/dump.ros" "executable" "./component-planner.ros") (:QUIT NIL)))))
53: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/etc/roswell/init.lisp\"))") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (217)) (ros:run '((:eval"(ros:quicklisp)")(:eval "(setf ql:*local-project-directories* '(#p\"/home/ls/CAP/\"))(ql:register-local-projects)")(:script "/etc/roswell/dump.ros""executable""./component-planner.... {10012C869F}>)))
54: (SB-IMPL::TOPLEVEL-INIT)
55: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
56: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
57: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 ERROR condition
make: *** [Makefile:16: component-planner] Error 1

**Comment by guicho271828** [comment]
Wow I never thought someone would try to actually build something I wrote 10 years ago! Let me check it this weekend

**Comment by guicho271828** [comment]
Hi, I fixed it. 
The compilation issue was my careless regression from refactoring.
There were few more issues due to outdated fast downward / planner-script (my own utility lib) / cgroup etc.
It no longer depends on cgroup.

Please try `make` and then `test.sh`.

**Comment by Little0213** [comment]
Thanks for your reply and the fixed code, it was very helpful for me

**Comment by guicho271828** [comment]
I hope you could run the experiment, if you are trying to compare mine with other algorithms.

**Comment by Little0213** [comment]
Hi!I'm running your code now, but when I run bash test.sh, I get an issue like the following.
rm: cannot remove '/tmp/lisptmp': No such file or directory
rm: cannot remove '/tmp/captest': No such file or directory
rm: cannot remove '/tmp/newtmp': No such file or directory
results goes to /tmp/captest/
test.sh: line 28: parallel: command not found
